### ISSUE TITLE
Is python 2.7.5 supported?

### ISSUE THREAD

**Issue by perfecto25** [Lucretiel/MakePass#3]
Looks like it doesnt run with py 2.7, is this for py3+ only?

```
 make_pass
Traceback (most recent call last):
  File "/usr/local/bin/make_pass", line 11, in <module>
    load_entry_point('makepass==0.11.0', 'console_scripts', 'make_pass')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/makepass/makepass.py", line 28
    yield from itertools.islice(
             ^
SyntaxError: invalid syntax
```

**Comment by perfecto25** [comment]
got it to work correctly by installing with pip3

sudo pip3 install makepass

**Comment by Lucretiel** [comment]
Yes, it's Python 3 only. It could be updated to Python 2, but [Python 2 is EoL in 7 months](https://pythonclock.org/), so I wanted to focus on Python 3 and have the flexibility to use Python 3 features.
